name: Linters

on:
  push:
    paths-ignore:
      - '.**'
      - '!.github/workflows/linters.yml'
      - '!.flake8'
      - 'README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flake8:
    name: Flake8 (Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pipenv'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --dev
      - name: Analyzing the code with flake8
        if: always()
        run: |
          pipenv run flake8